### ISSUE TITLE
Bug with same name characters

### ISSUE THREAD

**Issue by Lajt** [M1nistry/GuildStatus#1]
When you die, delete and create new character with same name as your previous.
You will see only this dead one in your program.
For example:
I died at 40lvl in 1month hc league
I delete character and create new one with same name
now im at 73lvl and in your program i see only my dead 40lvl character.

**Comment by M1nistry** [comment]
Aware of this. Something I've been meaning to detail to /u/trackpete as it's a limitation in his API I'm fairly sure. GGG can support it since they have a hidden unique ID to identify different characters by, however trackpete is using account.character as an ID.

Thanks though
